### ISSUE TITLE
How to extract attachments?

### ISSUE THREAD

**Issue by eaglebush** [knadh/go-pop3#3]
How do we extract attachments in the received mail?

**Comment by knadh** [comment]
Hi @eaglebush. The lib doesn't support attachments right now.

**Comment by iredmail** [comment]
@eaglebush you can use go-message package to walk messages parts and extract the attachments: https://github.com/emersion/go-message

**Comment by knadh** [comment]
+1. Since the lib returns the messag body as a `[]byte` slice, it can be parsed externally with a good parser. Since e-mail parsing isn't trivial and libs like emersion do a good job, it's best to keep it separate.
