### ISSUE TITLE
Q: How do you update inbox? 

### ISSUE THREAD

**Issue by icyrogue** [knadh/go-pop3#6]
Hello there, my question is simple and maybe even dumb, but how do you supposed to update messages in inbox without reconnecting to server?

**Comment by knadh** [comment]
Sorry, I don't really get the question. Update the e-mails where?

**Comment by icyrogue** [comment]
I'm sorry if I couldn't explain my question clear enough. I am trying to use pop3 to wait for new messages in my inbox and do some logic when I get a new message. After connection and auth, I call ```client.Stat() ``` once, then I call it once a minute or something to wait for new messages, but I don't get new messages. The count of messages in inbox which ```client.Stat()``` stays the same although there are definitely new messages

**Comment by knadh** [comment]
This isn't possible with the POP3 protocol, unfortunately. The only way to get updates from a POP mailbox is to poll by closing, reconnecting, refetching. If you want real time updates, you'd have to look at IMAP.
